name: release mirroring
on:
  push:
    branches:
      - release
permissions:
  contents: read
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: release
      - name: set SSH key
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "$SSH_KEY" > key.pem
          chmod 600 key.pem
      - name: add remote
        run: |
          git remote add release git@github.com:fuzzuf/fuzzuf
      - name: push
        env:
          GIT_SSH_COMMAND: ssh -i ./key.pem
        run: |
          git push release release:master
